### ISSUE TITLE
backtrace doesn't show the line of code executing the query

### ISSUE THREAD

**Issue by theonegri** [lightyear/sql-logging#12]
I run it 'out of the box' and got this:
```
2.1.1-railsexpress :004 > job.save
   (28.9ms)  BEGIN
    7 rows, 258 Bytes

  Jail Load (31.6ms)  SELECT  "jails".* FROM "jails" WHERE "jails"."email" = $1 LIMIT 1  [["email", "foo@bar.com"]]
    0 rows, 0 Bytes

    5 rows, 178 Bytes

    1 row, 2 Bytes

  Skill Load (30.8ms)  SELECT "skills".* FROM "skills" INNER JOIN "job_skills" ON "skills"."id" = "job_skills"."skill_id" WHERE "job_skills"."job_id" = $1  [["job_id", 27]]
    1 row, 74 Bytes

    6 rows, 227 Bytes

   (28.3ms)  ROLLBACK
 => false
2.1.1-railsexpress :005 >
```
On Rails 4.2.0 with PostgreSQL.

Am I doing something wrong?

**Comment by sjmadsen** [comment]
I'll be honest: it's been a really long time since I've used my own gem. Lately I've been working in the iOS world nearly full-time.

I haven't tested on Rails 4.2 and it's entirely possible that something within the framework has changed that breaks sql-logging.

**Comment by rob-murray** [comment]
If this gem does not get updated then this alternative [active-record-query-trace](https://github.com/ruckus/active-record-query-trace) worked OK for me on Rails 4.2.1

**Comment by mtyeh411** [comment]
i have found that this gem seems to be initializing `Rails.backtrace_cleaner` during application initialization and so when that happens `Rails.root` is equal to `nil`.  In Rails 4.2 this is a problem since `Rails::BacktraceCleaner` [now memoizes the value with a frozen string](https://github.com/rails/rails/commit/dfbcfafd9af046b3e8c79fe7309d31af6f82f9b2) used in that filter (which would be `'/'` when `sql-logging` is in use rather than `Rails.root`)

i submitted [a PR to active-record-query-trace](https://github.com/ruckus/active-record-query-trace/pull/13) so that it can be used in conjunction with `sql-logging` but would imagine that this needs fixing here as well

**Comment by mtyeh411** [comment]
submitted https://github.com/lightyear/sql-logging/pull/14 to fix this issue
